name: Build & Push Images

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Docker Login
        run: |
          echo ${{ secrets.ACR_PASSWORD }} | docker login ${{ secrets.ACR_LOGIN_SERVER }} -u ${{ secrets.ACR_USERNAME }} --password-stdin

      # 🔹 PRODUCT SERVICE
      - name: Build & Push Product
        run: |
          docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/product-service:v1 ./backend/services/products
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/product-service:v5

      - name: Scan Product Image (Trivy)
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ secrets.ACR_LOGIN_SERVER }}/product-service:v5
          format: table
          exit-code: 0

      # 🔹 AUTH SERVICE
      - name: Build & Push Auth
        run: |
          docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/auth-service:v1 ./backend/services/authenticate
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/auth-service:v1
      - name: Scan Auth Image (Trivy)
        uses: aquasecurity/trivy-action@master
        with:
         image-ref: ${{ secrets.ACR_LOGIN_SERVER }}/auth-service:v1
         format: table
         exit-code: 0
      # 🔹 ORDER SERVICE
      - name: Build & Push Order
        run: |
          docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/order-service:v1 ./backend/services/Order
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/order-service:v1
      - name: Scan Order Image (Trivy)
        uses: aquasecurity/trivy-action@master
        with:
         image-ref: ${{ secrets.ACR_LOGIN_SERVER }}/order-service:v1
         format: table
         exit-code: 0
      # 🔹 DELIVERY SERVICE
      - name: Build & Push Delivery
        run: |
         docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/delivery-service:v1 ./backend/services/delivery
         docker push ${{ secrets.ACR_LOGIN_SERVER }}/delivery-service:v1

     # 🔹 PAYMENT SERVICE
      - name: Build & Push Payment
        run: |
          docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/payment-service:v1 ./backend/services/payment
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/payment-service:v1